CREATE TABLE country
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    population INTEGER                                 NOT NULL,
    continent  VARCHAR(255),
    CONSTRAINT pk_country PRIMARY KEY (id)
);

CREATE TABLE country_event
(
    country_id BIGINT  NOT NULL,
    event_id   INTEGER NOT NULL,
    CONSTRAINT pk_country_event PRIMARY KEY (country_id, event_id)
);

CREATE TABLE event
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source     VARCHAR(255),
    date       date,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE event_event_type
(
    event_id      INTEGER NOT NULL,
    event_type_id INTEGER NOT NULL,
    CONSTRAINT pk_event_eventtype PRIMARY KEY (event_id, event_type_id)
);

CREATE TABLE event_type
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_type VARCHAR(255),
    CONSTRAINT pk_eventtype PRIMARY KEY (id)
);

ALTER TABLE country_event
    ADD CONSTRAINT fk_coueve_on_country FOREIGN KEY (country_id) REFERENCES country (id);

ALTER TABLE country_event
    ADD CONSTRAINT fk_coueve_on_event FOREIGN KEY (event_id) REFERENCES event (id);

ALTER TABLE event_event_type
    ADD CONSTRAINT fk_eveevetyp_on_event FOREIGN KEY (event_id) REFERENCES event (id);

ALTER TABLE event_event_type
    ADD CONSTRAINT fk_eveevetyp_on_event_type FOREIGN KEY (event_type_id) REFERENCES event_type (id);