CREATE TABLE analysis_feature_contribution
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    analysis_result_id BIGINT                                  NOT NULL,
    feature_name       VARCHAR(255)                            NOT NULL,
    feature_value      DOUBLE PRECISION                                ,
    contribution_score DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_analysisfeaturecontribution PRIMARY KEY (id)
);

CREATE TABLE analysis_narrative
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    analysis_result_id BIGINT                                  NOT NULL,
    audience           VARCHAR(255)                            NOT NULL,
    narrative          TEXT                                    NOT NULL,
    generated_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_analysisnarrative PRIMARY KEY (id)
);

CREATE TABLE analysis_result
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country_id    BIGINT                                  NOT NULL,
    period_start  date                                    NOT NULL,
    period_end    date                                    NOT NULL,
    anomaly_type  VARCHAR(20)                             NOT NULL,
    anomaly_score DOUBLE PRECISION                        NOT NULL,
    is_anomaly    BOOLEAN                                 NOT NULL,
    severity      VARCHAR(20),
    model_version VARCHAR(20)                             NOT NULL,
    analysed_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_analysisresult PRIMARY KEY (id)
);

ALTER TABLE analysis_result
    ADD CONSTRAINT unique_analysis_result UNIQUE (country_id, period_start, period_end, anomaly_type, model_version);

ALTER TABLE analysis_feature_contribution
    ADD CONSTRAINT FK_ANALYSISFEATURECONTRIBUTION_ON_ANALYSIS_RESULT FOREIGN KEY (analysis_result_id) REFERENCES analysis_result (id);

ALTER TABLE analysis_narrative
    ADD CONSTRAINT FK_ANALYSISNARRATIVE_ON_ANALYSIS_RESULT FOREIGN KEY (analysis_result_id) REFERENCES analysis_result (id);

ALTER TABLE analysis_result
    ADD CONSTRAINT FK_ANALYSISRESULT_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES country (id);

ALTER TABLE population_history
DROP
COLUMN country_code;

ALTER TABLE country
ALTER
COLUMN country_code TYPE VARCHAR(3) USING (country_code::VARCHAR(3));